### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by BrianPugh** [JeffWang987/MVSTER#1]
Thank you for publishing code for your work! I was wondering if you could add a `LICENSE` file to your repo? Thanks!

**Comment by JeffWang987** [comment]
> 
The LICENSE file is added, thanks for your suggestion.

**Comment by JeffWang987** [comment]
> Thank you for publishing code for your work! I was wondering if you could add a `LICENSE` file to your repo? Thanks!

The `LICENSE` file is added. Thanks for your suggestion!
