### ISSUE TITLE
Are DTU results reported in the paper trained on 640 or 1280?

### ISSUE THREAD

**Issue by ewrfcas** [JeffWang987/MVSTER#2]
Thanks for your good work! I have not seen any discussion of the input resolution in the paper.

**Comment by MaybeOjbk** [comment]
I'm also curious about the Ablation Study of your paper?  Are the depths trained in 1600 x1200 or  640 x 512? And also I want to know that does the high-resolution training strategy boost the depth quality rapidly

**Comment by cnexah** [comment]
Same question: is training on 1600 x1200 necessary? or we just train on 640 x 512 and test on 1600 x1200?

**Comment by JeffWang987** [comment]
To boost the performance, MVSTER* is trained on 1600 x1200 and then tested on 1600 x1200. In the ablation, we train on 640 x 512 and test on 864 x 1152.

**Comment by cnexah** [comment]
Thank you!
