### ISSUE TITLE
Is there any other way to download the dataset?

### ISSUE THREAD

**Issue by leeyegy** [JeffWang987/MVSTER#4]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/35657511/180697852-a5cbf805-139f-417b-8c97-6d2b132be1e1.png">

**Comment by leeyegy** [comment]
THANKS for your great work.
An error comes to me while trying to download the preprocessed [DTU training data](https://drive.google.com/file/d/1eDjh-_bxKKnEuz5h-HXS7EDJn59clx6V/view).

Any suggestions would be greatly appreciated~

**Comment by SibylGao** [comment]
Same. idm or wget do not work for me. ( I'm in mainland china )

**Comment by SibylGao** [comment]
Try Baidu Cloud: [https://pan.baidu.com/s/1Wb9E6BWCJu4wZfwxm_t4TQ#list/path=%2Fmvsnet%2Ftraining_data](DTU_training). 
Extraction code: s2v2

**Comment by leeyegy** [comment]
Thanks a lot for your help~
